name: Publish Helm Library Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm-library/**'
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Package and Push Charts
        run: |
          cd helm-library

          for chart in base-deployment base-service base-hpa base-ingress base-secret; do
            echo "Packaging $chart"
            helm package $chart
            VERSION=$(helm show chart $chart | grep version | awk '{print $2}')
            helm push ${chart}-${VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
          done
