apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: scaleway-cluster-store
spec:
  provider:
    scaleway:
      projectId: {{ required "projectId is required" .Values.projectId }}
      region: {{ required "region is required" .Values.region }}
      accessKey:
        secretRef:
          name: {{ required "credentialSecretName is required" .Values.credentialSecretName }}
          key: access-key
          namespace: {{ .Values.credentialNamespace }}
      secretKey:
        secretRef:
          name: {{ required "credentialSecretName is required" .Values.credentialSecretName }}
          key: secret-key
          namespace: {{ .Values.credentialNamespace }}
